---
data:
  extends:
    file: docker-compose-common.yml
    service: data

redis:
  extends:
    file: docker-compose-common.yml
    service: redis
  volumes_from:
  - data
  restart: always

wheatley:
  image: quay.io/smashwilson/wheatley
  links:
  - "redis:redis"
  environment:
    REDIS_URL: redis://redis/
    HUBOT_SLACK_TOKEN:
  restart: always
