---
data:
  image: redis:3.0
  volumes:
  - /data
  command: true

redis:
  image: redis:3.0
  command: redis-server --appendonly yes

wheatley:
  build: .
  environment:
    REDIS_URL: redis://redis/
