#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)
cd ${ROOT}

[ -f ${ROOT}/env.sh ] || {
  echo "${ROOT}/env.sh does not exist." 2>&1
  echo 2>&1
  echo " cp ${ROOT}/env.example.sh ${ROOT}/env.sh" 2>&1
  echo " \${EDITOR} env.sh" 2>&1
  echo 2>&1
  exit 1
}

source ${ROOT}/env.sh

COMPOSE=docker-compose --file ${ROOT}/docker-compose-production.yml

${COMPOSE} build
${COMPOSE} up -d
